# Generated by Django 3.2.5 on 2021-07-19 07:47

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('starproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.IntegerField(choices=[(1, 'very low'), (2, '2'), (3, '3'), (4, '4'), (5, 'Avarage'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, 'Exellent')], default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='design',
            field=models.IntegerField(choices=[(1, 'very low'), (2, '2'), (3, '3'), (4, '4'), (5, 'Avarage'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, 'Exellent')], default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='usability',
            field=models.IntegerField(choices=[(1, 'very low'), (2, '2'), (3, '3'), (4, '4'), (5, 'Avarage'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, 'Exellent')], default=0),
        ),
        migrations.CreateModel(
            name='ProfileApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('bio', models.TextField()),
                ('profile_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starproject.project')),
                ('projects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
